Quiz/urls.py
from django.conf.urls import include,url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views

#from .views import GramConceptList, GramConceptCreate, GramConceptUpdate, GrammarUpdate

app_name = 'Quiz'

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.dashboard, name='dashboard'),   
    url(r'^gramconcept/$', views.GramConceptList.as_view(), name='gramconcept-list'),
    url(r'^gramconcept/create/$', views.GramConceptCreate.as_view(), name='gramconcept-create'),
    url(r'^gramconcept/update/(?P<pk>[0-9]+)/$', views.GramConceptUpdate.as_view(), name='gramconcept-update'),
    url(r'^gramconcept/delete/(?P<pk>[0-9]+)/$', views.GramConceptDelete.as_view(), name='gramconcept-delete'),
    url(r'^grammar/$', views.GrammarList.as_view(), name='grammar-list'),
    url(r'^grammar/create/$', views.GrammarCreate.as_view(), name='grammar-create'),
    url(r'^grammar/update/(?P<pk>[0-9]+)/$', views.GrammarUpdate.as_view(), name='grammar-update'),
    url(r'^grammar/delete/(?P<pk>[0-9]+)/$', views.GrammarDelete.as_view(), name='grammar-delete'),
    url(r'^prep_select_course/$', views.prep_select_course, name='prep_select_course'),
    url(r'^select_course/$', views.select_course, name='select-course'),
    url(r'^signup_course/$', views.signup_course, name='signup-course'),
    url(r'^register_student_to_course/$', views.register_student_to_course, name='register-student-to-course'),
    url(r'^reset_all_student_progress/$', views.reset_all, name='reset-all'),
    url(r'^new_question/(?P<stage_id>[0-9]+)/$', views.new_question, name='new-question'),
    url(r'^new_question_from_sentence/(?P<sentence_id>[0-9]+)/$', views.new_question_from_sentence, name='new_question_from_sentence'),
    url(r'^new_question/$', views.new_question, name='new-question'),    
    url(r'^gram_create/$', views.gram_create, name='gram-create'), 
    url(r'^gram_update/(?P<id>[0-9]+)/$', views.gram_update, name='gram-update'), 
    url(r'^grammar-restage/(?P<gram_id>[0-9]+)/(?P<active_tab>[a-z]+)/$', views.grammar_restage, name='grammar-restage'),     
    url(r'^initial_placement_init/$', views.initial_placement_init, name='initial_placement_init'),
    url(r'^run_initial_placement/$', views.run_initial_placement, name='run_initial_placement'),    
    url(r'^reset_all/$', views.reset_all, name='reset-all'),    
    url(r'^integrity_check/$', views.integrity_check, name='integrity_check'),    
    url(r'^integrity_check/(?P<course_id>[0-9]+)/$', views.integrity_check, name='integrity_check'),    
    url(r'^assessment_init/$', views.assessment_init, name='assessment_init'), 
    url(r'^assessment_schedule_qs/$', views.assessment_schedule_qs, name='assessment_schedule_qs'),
    url(r'^assessment_report/$', views.assessment_report, name='assessment_report'),
    url(r'^assessment_ask_qs/$', views.assessment_ask_qs, name='assessment_ask_qs'),
    url(r'^question_score/$', views.question_score, name='question-score'),
    url(r'^ajax/submit_answer/$', views.ajax_submit_answer, name='ajax_submit_answer'),
    url(r'^add_stage/$', views.add_stage, name='add_stage'),
    url(r'^example_questions/(?P<grammar_id>[0-9]+)/$', views.example_questions, name='example_questions'), 
    
    
]
# 
# 
# urlpatterns = [ # ... 
#    url( r'author/ add/ $', AuthorCreate.as_view(), name =' author_add'), 
#    url( r'author/(? P < pk >[ 0-9] +)/ $', AuthorUpdate.as_view(), name =' author_update'), 
#    url( r'author/(? P < pk >[ 0-9] +)/ delete/ $', AuthorDelete.as_view(), name =' author_delete'),


#     # ex: /poll/2/
#     url(r'^(?P<topic_id>[0-9]+)/$', views.tally, name='tally'),
#     # ex: /poll/detail/e23d2q45/
#     url(r'^detail/(?P<token_id>[a-z0-9]+)/$', views.detail, name='detail'),
#     # Ex: /poll/vote/    because of csrf tokens, may not need any more than "vote"
#     url(r'^vote/$', views.vote, name='vote'),
#     # Ex: /poll/newtopic/
#     url(r'^topicf/$', views.CreateTopic.as_view(), name='CreateTopic'),

lang/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lang import views as core_views

urlpatterns = [
    url(r'^quiz/', include('Quiz.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^new_login/', core_views.new_login, name='new_login'),    
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/signup/$', core_views.signup, name='signup'),
    url(r'^accounts/logout/$', core_views.logout_view, name='logout_view'),
    
]

Quiz/models/attempt.py
from django.db import models
from django.contrib.auth.models import User
from .entry import Entry
import logging

class AttemptManager(models.Manager):
    def q_type_of(self, target_type, results_desired=1, language=None):
        # returns questions with the greatest percentage of target_type self_assessments.
        
        q_scores = {} # dictionary to record highest scoring questions
#        Qs = Attempt.objects.order_by().values('question').distinct()    # could also do this operation on question_progress table, but attempt table keeps records even for deleted users
        for q in Qs:
            # skip Qs of another language
            if (language is not None):
                if q.question.grammar.stage.target_language != language:
                    continue # skip the rest of this iteration
            
            # find all attempts for this question
            wrong_count = 0
            As = Attempt.objects.filter(question = q)    
            for a in As:
                # iterate through each attempt and count wrongs
                if a.self_assesment == target_type:
                    wrong_count += 1
            q_scores[q] = wrong_count/len(As)
        
        
        results = []
        return_count = min(results_desired,len(q_scores))
        for i in range(return_count):
            r = max(q_scores, key=q_scores.get)
            results.append(r)
            del(q_scores[r])
        return results

    def hardest_questions(self, results_desired=1, language=None):
        return self.q_type_of(Attempt.WRONG,language,results_desired)
    
    def most_reported_questions(self, results_desired=1, language=None):
        return self.q_type_of(Attempt.REPORT,language,results_desired)

class Attempt(models.Model):
    # User attempt and results at a question
    # Records their result, points to an Entry related to what they typed, records the user, ELO and variance at time

    CORRECT = Entry.CORRECT
    WRONG = Entry.WRONG
    REPORT = Entry.REPORT
    A_TYPE_CHOICES = ((CORRECT, 'Right'), (WRONG, 'Wrong'), (REPORT, 'There is a problem with the question'))   

    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    raw_entry = models.CharField(max_length=200, help_text="entry text")
    entry = models.ForeignKey('Entry', on_delete=models.CASCADE)
    assessment = models.CharField(max_length=1,choices=A_TYPE_CHOICES, db_index=True)   
    feedback = models.CharField(max_length=200, help_text="What is it about the question that makes it unclear or misleading",blank=True)
    score = models.FloatField(null=True, blank=True, help_text="score of the user when this attempt was made - only recorded if variance below a certain threshold, otherwise null")    
    variance = models.FloatField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    #objects = AttemptManager()

    def save(self, *args, **kwargs):
        super(Attempt, self).save(*args, **kwargs)

    def __str__(self):
        return str([self.entry])

Quiz/models/comment.py
from django.db import models
from django.contrib.auth.models import User
import logging

class Comment(models.Model):
    # A comment can be about a model instance of any model type, 
    # hence comment model does not have its own parent_model foreign key.
    
    text = models.TextField(help_text="Comment")
    language = models.ForeignKey('Language', null=True, on_delete=models.CASCADE)
    parent = models.ForeignKey('Comment', null=True, blank=True, on_delete=models.PROTECT, db_index=True, help_text="If this comment is in reply to a previous comment")
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    last_edited = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.text)

    def save(self, *args, **kwargs):
        super(Comment, self).save(*args, **kwargs)

Quiz/models/course.py
from django.db import models
from django.contrib.auth.models import User
from .language import Language
from .stage import Stage
import logging

# A course is defined as teaching target_language
# titles contains the course name in the native_languages that are adequately prepared for this course

class Course(models.Model):
    titles = models.ManyToManyField('Sentence',blank=True)
    target_language = models.ForeignKey('Language', related_name='target_courses', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    last_edited = models.DateField(auto_now=True)

    def __str__(self):
        return (self.target_language.anglicized_name)

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)
        if not self.stage_set.exists():
            Stage.objects.create(position=1,course=self,author=self.author)
        log = logging.getLogger(__name__)
        log.info(("Model Course Instance saved:"+str(self)).encode("utf-8"))

    def lowest_stage(self):
        return self.stage_set.order_by("position").first()

    def native_languages(self):
        # returns all native_languages this course is available in
        lang_ids = self.titles.values_list('language', flat=True)
        return Language.objects.filter(id__in=lang_ids)

    def title_in(self,language):
        title = self.titles.filter(language=language).first()
        if title is not None:
            title = title.text
        else:
            title = "NO_TITLE"      
        return title    

    def determine_stage(self,score):
        # Given an ELO score, returns the stage most appropriate (first stage with a score higher than 'score')
        # If the score is above all available stages, returns last registered stage
        return self.stage_above(score)

    def stage_above(self,score):
        last_stage = None
        for stage in Stage.objects.filter(course=self).order_by("position"):
            last_stage = stage
            if stage.score() > score:
                break
        return last_stage
        
    def stage_below(self,score):
        last_stage = None
        for stage in Stage.objects.filter(course=self).order_by("position"):
            if stage.score() > score:
                break
            last_stage = stage                
        return last_stage

Quiz/models/gram_concept.py
from django.db import models
from django.contrib.auth.models import User
import logging

# A Grammar Concept gives the abstract linguistical name to grammars as implemented in
# different languages. Future tense is expressed in varying grammars in different languages
# but future tense as a gramattical concept will exist in most.
# Grammar concepts help tie sentences of different languages together as related.

class GramConcept(models.Model):
    title = models.CharField(max_length=200, help_text="Linguistical name")
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    last_edited = models.DateField(auto_now=True)
    
    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        super(GramConcept, self).save(*args, **kwargs)
        log = logging.getLogger(__name__)
        log.info("Model GramConcept Instance saved:"+str(self))
        

Quiz/models/language.py
from django.db import models
from django.contrib.auth.models import User
import logging

# Languages are used to populate native_language and target_language fields
# Each language has a name, written in the script of that language, and an
# anglicized_name expressing the English name for that language.

class Language(models.Model):
    name = models.CharField(max_length=200, unique=True)
    anglicized_name = models.CharField(max_length=200, unique=True)
    iso693_2 = models.CharField(max_length=8, help_text="Please find the correct code at: https://www.loc.gov/standards/iso639-2/php/code_list.php") 
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (self.anglicized_name)

    def save(self, *args, **kwargs):
        super(Language, self).save(*args, **kwargs)
        log = logging.getLogger(__name__)
        log.info("Model Language Instance saved:"+str(self))

    class Meta:
        ordering = ['anglicized_name']

Quiz/models/question.py
from django.db import models
from django.contrib.auth.models import User
from common import massage
import logging

# Questions are pairs of sentences. One being the front (the question), and the other being
# the back (the answer). Which is written in the target_language and which in the 
# native_language is arbitrary. 
# Questions can be marked as key_cases, ensuring they are displayed first to a student.
# Also they can provide a hint (displayed when the front is shown), and an explanation
# (displayed when the back is shown.) A question belongs to a single grammar, even though
# its sentences could contain multiple grammars. The question's grammar determines when the
# question will appear.
# The question score starts as that of the grammar's base score, but with time
# increases or decreases to reflect the question's unique difficulty as determined by student
# success in successfully answering it.

class QuestionQuerySet(models.QuerySet):
    def best_quality(self):
    # Questions should be selected by an algorithm. Low-tested Qs prioritised to get feedback
    # and to determing their ELOs, and prioritising Qs with approval by users (low/no complaints).
        return self.first() # placeholder

# class QuestionManager(models.Manager):
# #     def get_queryset(self):
# #         return QuestionQuerySet(self.model, using=self._db)
# 
#     def best_quality(self):
#     # Questions should be selected by an algorithm. Low-tested Qs prioritised to get feedback
#     # and to determing their ELOs, and prioritising Qs with approval by users (low/no complaints).
# #        return self.get_queryset().first() # placeholder
#         return super(QuestionManager, self).get_queryset().first()

class Question(models.Model):
    front = models.ForeignKey('Sentence', related_name='question_fronts', help_text='question sentence')
    back = models.ForeignKey('Sentence', related_name='question_backs', help_text='answer sentence') 
    target_language = models.ForeignKey('Language', related_name='question_target_language', on_delete=models.CASCADE)
    native_language = models.ForeignKey('Language', related_name='question_native_language', on_delete=models.CASCADE)
    hint = models.TextField(help_text="Written in the native language, a hint that directs a user of this language towards selecting the correct answer. Useful where the target language may allow multiple equivalents",blank=True) 
    explanation = models.TextField(help_text="Written in the native language, an explanation to peculiarities in the answer.",blank=True)
    grammar = models.ForeignKey('Grammar' , null=True, blank=True, db_index=True)
    simplified = models.CharField(max_length=200, help_text="massaged entry text", blank=True, null=True) # internal hashprocessing to make comparing similar entries easier
    score = models.FloatField(null=True, blank=True, db_index=True, help_text="starts as grammar ELO. If users continue to find this Q hard, this will be indicated by this score creeping upwards.")    
    variance = models.FloatField(default=250) # note - actual applied variance is modified by the student's variance, the greater the student's variance, the less impacted the question should be by that student's result
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    last_edited = models.DateField(auto_now=True)

#    objects = QuestionManager()
    objects = QuestionQuerySet.as_manager() 
    
    def rescore(self, score):
        # updates question ELO score
        self.score = max(score, 0)
        self.variance = self.variance * 0.9
        self.save()


    def save(self, *args, **kwargs):
        # Primarily this is to be called when the instance is initially created. setting the inital score value.
        # But re-saving questions can also be useful to update simplified field if the hash method changes.
        if self.grammar is None:
            # check which sentence is in target language
            if self.front.language == self.target_language:
                tl_sentence = self.front
            elif self.back.language == self.target_language:
                tl_sentence = self.back
            else:
                raise ValidationError # neither sentence is in the questions target_language            
            # find highest grammar associated with the tl_sentence
            self.grammar = tl_sentence.grammars.filter().order_by('-score').first()
            if self.grammar is None:
                raise ValidationError
        self.simplified = massage.simplify(
            self.back.text,
            native=self.native_language.iso693_2,
            target=self.target_language.iso693_2,
        )
        if self.score is None:
            self.score = self.grammar.score # by default, questions start off at their grammar's base score
        # save as the question's grammar        
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return str([self.front, self.back])

Quiz/templates/Quiz/assessment_report.html
{% extends 'base.html' %}

{% block title %}Learning Summary{% endblock %}

{% block content %}

Here are the grammars you should be focusing on next in your learning:
	<ul>
	{% for focus in focus_titles %}
		<li>{{ focus }}</li>
	{% endfor %}
	</ul>

	<p><a href="{% url "Quiz:dashboard" %}">Return to dashboard</a></p>
{% endblock %}

Quiz/templates/Quiz/gram_create.html
{% extends 'base.html' %}

{% block title %}Add New Grammars{% endblock %}

{% block content %}
<div class="container">

  <ul class="nav nav-tabs">
    <li
        {% if active_tab == "existing" %}
    	 	class="active">
	    {% else %}
	    	>
	    {% endif %}	    
	    <a data-toggle="tab" href="#existing">Existing Stage Grammars</a></li>
    <li
		{% if active_tab == "unassigned" %}
    	 	class="active">
	    {% else %}
	    	>
	    {% endif %}
		<a data-toggle="tab" href="#unassigned">Grammars unassigned to a Stage</a></li>
    <li
	    {% if active_tab == "create" %}
    	 	class="active">
	    {% else %}
	    	>
	    {% endif %}
    	<a data-toggle="tab" href="#create">Create New</a></li>
  </ul>

  <div class="tab-content">
    <div id="existing" 
    {% if active_tab == "existing" %}
    	class="tab-pane fade in active">
    {% else %}
    	class="tab-pane fade">
    {% endif %}
		<h3>Existing Stage Grammars</h3>
		<table class="table">	
		{% for counter,type in countlist.items %}
			{% if type == "stage" %}
			<thead class="thead-inverse">
				<tr>
					<th>
						Stage {{ stage_titles|get_item:counter }}
					</th>
				</tr>
			</thead>
			{% elif type == "grammar" %}
			<tr>
				<td>{{ grammar_concepts|get_item:counter }}<a href="{% url 'Quiz:gram-update' grammar_id|get_item:counter %}">({{ grammar_titles|get_item:counter }})</a></td>
				<td>
					{% if grammar_explanation|get_item:counter %}
						<button type="button" class="btn btn-success" id="grammar_explanation_{{ counter }}">Explanation</button>
					{% else %}
						<button type="button" class="btn btn-warning" id="grammar_explanation_{{ counter }}">Explanation</button>
					{% endif %}			
				</td>
				<td>
					<a href="{% url 'Quiz:example_questions' grammar_id|get_item:counter %}">
						{% if grammar_example_question|get_item:counter %}
							<button type="button" class="btn btn-success" id="grammar_example_question_{{ counter }}">Example Question<span class="badge badge-pill badge-success">{{ questions|get_item:counter }}</span></button>
						{% else %}
							<button type="button" 
							{% if questions|get_item:counter == 0 %}
								class="btn btn-danger" 
							{% else %}
								class="btn btn-warning"
							{% endif %}
								id="grammar_example_question_{{ counter }}">Example Question<span class="badge badge-pill badge-success">{{ questions|get_item:counter }}</span></button>
						{% endif %}			
					</a>
				</td>
				<td>
					<form action="{% url 'Quiz:grammar-restage' grammar_id|get_item:counter 'existing' %}" method="post">{% csrf_token %}
						<div class="btn-group">
							<button type="button" id="grammar_restage_{{ counter }}" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Stage<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								{% for key,stg in stages.items %}
								
									<li><button type="submit" name="stage" value = "{{ stg.id }}" class="btn-link"> {{ stg.title }}</button></li>
								{% endfor %}
							</ul>
						</div>
					</form>
				</td>
				<td>
					<a href="{% url 'Quiz:grammar-delete' grammar_id|get_item:counter %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></button></a>
	  			</td>
	  		</tr>
	  		{% endif %}
		{% endfor %}
		</table>
		<p><a href="{% url 'Quiz:add_stage'%}"> <button class="btn btn-primary" value="">Add additional stage</button></a></p>
    </div>


    <div id="unassigned" 
    {% if active_tab == "unassigned" %}
    	class="tab-pane fade in active">
    {% else %}
    	class="tab-pane fade">
    {% endif %}
      	<h3>Grammars unassigned to a Stage</h3>
		<table class="table">	
		{% for key,grm in unassigned_grammars.items %}
			<tr>
				<td><a href="{% url 'Quiz:grammar-update' grm.id %}">{{ grm.title }}</a> - {{ grm.gc_title }}</td>
				<td>
					{% if grm.explanation != "" %}
						<button type="button" class="btn btn-success" id="u_grammar_explanation_{{ grm.id }}">Explanation</button>
					{% else %}
						<button type="button" class="btn btn-warning" id="u_grammar_explanation_{{ grm.id }}">Explanation</button>
					{% endif %}			
				</td>
				<td>
					{% if grm.example_question %}
						<button type="button" class="btn btn-success" id="u_grammar_example_question_{{ grm.id }}">Example Question</button>
					{% else %}
						<button type="button" class="btn btn-warning" id="u_grammar_example_question_{{ grm.id }}">Example Question</button>
					{% endif %}			
				</td>
				<td>
					<form action="{% url 'Quiz:grammar-restage' grm.id 'unassigned' %}" method="post">{% csrf_token %}
						<div class="btn-group">
							<button type="button" id="grammar_restage_{{ counter }}" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Change stage<span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								{% for key,stg in stages.items %}
									<li><button type="submit" name="stage" value="{{stg.id}}" class="btn-link">{{stg.title}}</button></li>
								{% endfor %}
							</ul>
						</div>
					</form>
				</td>
				<td>
					<a href="{% url 'Quiz:grammar-delete' grm.id %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></button></a>
	  			</td>
	  		</tr>
	  	{% endfor %}	
  		</table>			
    </div>


    <div id="create" 
    {% if active_tab == "create" %}
    	class="tab-pane fade in active">
    {% else %}
    	class="tab-pane fade">
    {% endif %}
	<form method='POST' action=''>{% csrf_token %}
		<h3>Create New Grammar</h3>
		<div class="row" rows="6">
			<label for="id_Title">
				<div class="col-md-6">
					Title:				
					<textarea id="id_Title" name="Title" class="form-control col-xs-12" rows="1"></textarea>
				</div>
			</label>
			<div class="col-md-6">
				<label for="id_Explanation">Explanation:</label>
				<textarea id="id_Explanation" name="Explanation" class="form-control col-xs-12" rows="5"></textarea>
			</div>
		</div>
		<div class="row"><div class="col-md-12"><label for="id_Title">Grammar Concept:</label></div></div>
		<div class="row">
			<div class="col-md-12">				
				{% for g_concept in uninstantiated_gram_concepts %}
					<span class="button-checkbox">
						<button type="submit" class="btn btn-warning" name="GramConcept" value="{{ g_concept.id }}">
							{{ g_concept.title }}
						</button>
					</span> . 
				{% endfor %}
				{% for g_concept in inst_gram_concepts %}
					<span class="button-checkbox">
						<button type="submit" class="btn btn-success" name="GramConcept" value="{{ g_concept.id }}">
							{{ g_concept.title }}
						</button>
					</span> . 
				{% endfor %}
			</div>
		</div> 
	</form>
    </div>
  </div>
</div>
{% endblock %}


{% block javascript %}
	// reveal stage's grammar and highlight button
	$("body").click(function(e){
		if (e.target.id.startsWith("stage_button_")) {
			var but_id_num = e.target.id.replace("stage_button_","")
			var checkbox_id = "#stage_checkbox_" + but_id_num; 
			var gram_id = "#stage_grammar" + but_id_num;
			if ($(e.target).attr('class') == 'btn btn-success') {
				$(e.target).removeClass("btn btn-success").addClass("btn btn-default");
				$(gram_id).hide();
			} else if ($(e.target).attr('class') == 'btn btn-default') {
				$(e.target).removeClass("btn btn-default").addClass("btn btn-success");
				$(gram_id).show();
			};
			$(checkbox_id).prop('checked', !$(checkbox_id).is(':checked')) // inverse check
		};
	});

	// handles ticking of grammar points
	$(function () {
	    $('.button-checkbox').each(function () {
	        // Settings
	        var $widget = $(this),
	            $button = $widget.find('button'),
	            $checkbox = $widget.find('input:checkbox'),
	            color = $button.data('color'),
	            settings = { 									// unique to grammars
	                on: {
	                    icon: 'glyphicon glyphicon-check'
	                },
	                off: {
	                    icon: 'glyphicon glyphicon-unchecked'
	                }
	            };
	
	        // Event Handlers
	        $button.on('click', function () {
	            $checkbox.prop('checked', !$checkbox.is(':checked'));
	            $checkbox.triggerHandler('change');
	            updateDisplay();
	        });
	        $checkbox.on('change', function () {
	            updateDisplay();
	        });
	
	        // Actions
	        function updateDisplay() {
	            var isChecked = $checkbox.is(':checked');
	
	            // Set the button's state
	            $button.data('state', (isChecked) ? "on" : "off");
	
	            // Set the button's icon								// grammar only
	            $button.find('.state-icon')
	                .removeClass()
	                .addClass('state-icon ' + settings[$button.data('state')].icon);
	
	            // Update the button's color
	            if (isChecked) {
	                $button
	                    .removeClass('btn-default')
	                    .addClass('btn-' + color + ' active');
	            }
	            else {
	                $button
	                    .removeClass('btn-' + color + ' active')
	                    .addClass('btn-default');
	            }
	        }
	
	        // Initialization
	        function init() {
	
	            updateDisplay();
	
	            // Inject the icon if applicable
	            if ($button.find('.state-icon').length == 0) {
	                $button.prepend('<i class="state-icon ' + settings[$button.data('state')].icon + '"></i> ');
	            }
	        }
	        init();
	    });
	});
{% endblock %}

Quiz/templates/Quiz/gramconcept_list.html
{% extends 'base.html' %}

{% block title %}Grammar Concept List{% endblock %}

{% block content %}

	<ul>

	{% for gramC in object_list %}
	    <li>{{ gramC.title }} 
	    	| <a href="{% url 'Quiz:gramconcept-update' gramC.id %}">Update</a>
	    	| <a href="{% url 'Quiz:gramconcept-delete' gramC.id %}">Delete</a> 
	    </li>
	{% empty %}
	    <li>No Grammar Concepts found.</li>
	{% endfor %}

	</ul>

<a href="{% url 'Quiz:gramconcept-create'%}">Create a new entry</a>

{% endblock %}

Quiz/templates/Quiz/model_form.html
{% extends 'base.html' %}

{% block title %}Create/Update {{ model_name }}{% endblock %}

{% block content %}
	
{% include "Quiz/form_snippet.html" %}

	<a href="{% url 'Quiz:dashboard'%}">Dashboard</a>

{% endblock %}

{% block javascript %}
	// tooltip hover
	$(document).ready(function(){
	    $('[data-toggle="tooltip"]').tooltip();   
	});
{% endblock %}

Quiz/templates/Quiz/select_course.html
{% extends 'base.html' %}

{% block title %}Choose which course you would like to study{% endblock %}

{% block content %}
	<div class="well">
		<form action="{% url 'Quiz:select-course' %}" method="post">
			{% csrf_token %}
		    {% for course in registered_courses %}
			    <p>
				    <input type="radio" name="choice" id="course{{ forloop.counter }}" value="{{ course.id }}" />
				    <label for="course{{ forloop.counter }}">{{ course.title }}</label>
				</p>
			{% endfor %}
			<input type="submit" value="Select" />
		</form>
	</div>
		
	<a href="{% url "Quiz:signup-course" %}">Sign up for a new course</a>
{% endblock %}